### ISSUE TITLE
作者好，训练测试还不能运行吧？指定的.yaml文件不存在

### ISSUE THREAD

**Issue by ustczhouyu** [hustvl/BMaskR-CNN#1]
作者好，训练测试还不能运行吧？指定的.yaml文件不存在，期待早日发布

**Comment by wondervictor** [comment]
目前是可以运行的，请问缺少哪一个yaml文件呢  
[configs](https://github.com/hustvl/BMaskR-CNN/tree/master/projects/BMaskR-CNN/configs)

**Comment by zzzmm1** [comment]
请问下作者，模型测试的时候需要用到boundary的预测结果吗，还是就是根据有boundary监督训练出来的mask结果来预测的？

**Comment by wondervictor** [comment]
@zzzmm1 目前版本中，测试时不再需要boundary结果，在训练时通过boundary监督能够帮助mask更好的去捕捉到boundary的细节。

**Comment by Min-Juan** [comment]
请问一下作者，BMask模型下载不下来是什么情况，如果之前已经安好了detectron2，对于你这里新增加的BMask，下载后还需要重新编译吗？

**Comment by wondervictor** [comment]
@Min-Juan BMask R-CNN COCO预训练模型已经上传到了OneDrive上；如果装好了detectron2，就不再需要重新编译了。

**Comment by wondervictor** [comment]
No more response, closed!
