### ISSUE TITLE
What is different between Cascade BMask R-CNN and X101-FPN in detectron2 ?

### ISSUE THREAD

**Issue by charlescho64** [hustvl/BMaskR-CNN#11]
Hello, 

I have question about your work.
It seems X101-FPN (detectron2's result table) is better than R-101. 
If your model use X101-FPN baseline, is it much better?  So if you didn't, is there some reason?

**Comment by wondervictor** [comment]
@charlescho64 Sure, ResNeXt-101-FPN performs better than ResNet-101-FPN, and the conclusion also holds in BMask R-CNN. Due to the computation and memory budget as well as the limitation of GPUs, we didn't adopt the ResNeXt-101-FPN.

**Comment by charlescho64** [comment]
@wondervictor  Thank you for your reply. your job is very impressive.

**Comment by charlescho64** [comment]
@wondervictor 
Could you give me the way to use "RestNeXt-101-FPN" for training in your model(BMASK)?

**Comment by wondervictor** [comment]
@charlescho64 You can refer to this config file [mask_rcnn_X_101_32x8d_FPN_3x.yaml](https://github.com/hustvl/BMaskR-CNN/blob/master/configs/COCO-InstanceSegmentation/mask_rcnn_X_101_32x8d_FPN_3x.yaml#L6) which includes `ResNeXt-101-FPN`.

**Comment by charlescho64** [comment]
@wondervictor  Thank you.
