### ISSUE TITLE
Cityscapes model link seems to be wrong

### ISSUE THREAD

**Issue by bowenc0221** [hustvl/BMaskR-CNN#2]
<img width="202" alt="Screen Shot 2020-07-23 at 7 47 06 PM" src="https://user-images.githubusercontent.com/25308473/88356607-4b579c80-cd1d-11ea-8f30-bb581db4bb54.png">

This is what I get by clicking the Cityscapes model line, should it be a R50 model?
Could you check if you put the correct link?

Thanks.

**Comment by wondervictor** [comment]
Thanks～ The link has been fixed.

**Comment by bowenc0221** [comment]
Thanks
