### ISSUE TITLE
other datasets

### ISSUE THREAD

**Issue by wmrenr** [hustvl/BMaskR-CNN#24]
I would like to know how to train and test other datasets with bmask-rcnn network？

**Comment by wondervictor** [comment]
Hi @wangxueping78, BMask R-CNN is developed based on detectron2, and you can refer to the [documentation for more details about using custom datasets](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html). You can also convert your custom dataset into the COCO format and then adopt COCO dataloader to load your custom dataset.

**Comment by wmrenr** [comment]
Ok，I will try it！



发自我的iPhone


------------------ Original ------------------
From: Tianheng Cheng ***@***.***&gt;
Date: Thu,Mar 31,2022 11:17 PM
To: hustvl/BMaskR-CNN ***@***.***&gt;
Cc: wangxueping78 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [hustvl/BMaskR-CNN] other datasets (Issue #24)





 
Hi @wangxueping78, BMask R-CNN is developed based on detectron2, and you can refer to the documentation for more details about using custom datasets. You can also convert your custom dataset into the COCO format and then adopt COCO dataloader to load your custom dataset.

**Comment by wmrenr** [comment]
> Hi @wangxueping78, BMask R-CNN is developed based on detectron2, and you can refer to the [documentation for more details about using custom datasets](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html). You can also convert your custom dataset into the COCO format and then adopt COCO dataloader to load your custom dataset.
I registered my own dataset and started training, I got an error: RuntimeError: CUDA out of memory. Tried to allocate 626.00 MiB...... , what should I do？
My own dataset is much smaller than the coco dataset,but I only have one gpu, which is 3080Ti.

**Comment by wondervictor** [comment]
The default batch size is 16. You can reduce the batch size `SOLVER.IMS_PER_BATCH` to fit your GPU, e.g., 4 batch per GPU. Besides, you need to change the training schedule, including the max iterations, learning rate.

**Comment by wmrenr** [comment]
Oh,I have reduced the batch size SOLVER.IMS_PER_BATCH=1 in the follor 'BMaskR-CNN-master/detectron2/config/defaults.py', and decreased the max iterations, learning rate. I still  got an error: RuntimeError: CUDA out of memory........

**Comment by wondervictor** [comment]
You need to change it in the config-file, e.g., [bmask_rcnn_R_101_FPN_1x.yaml](https://github.com/hustvl/BMaskR-CNN/blob/c74b0bd3ed47bf4aaa5c211c4e31eddc78fdc636/projects/BMaskR-CNN/configs/bmask_rcnn_R_101_FPN_1x.yaml#L15). In each training, the config-file will update the values in the `defaults.py`.

**Comment by wmrenr** [comment]
Oh,you are right.I set IMS_PER_BATCH: 4,MAX_ITER: 10000, starting training.

**Comment by wmrenr** [comment]
I enter the command in the evaluation phase，‘ python train_broccoli_net.py --config-file configs/bmask_rcnn_R_101_FPN_1x.yaml --num-gpus 1 --eval-only output/bmask_rcnn_r101_1x/model_final.pth‘，but I got an error,'AssertionError: Override list has odd length: ['output/bmask_rcnn_r101_1x/model_final.pth']; it must be a list of pairs'?what it means?

**Comment by wondervictor** [comment]
the complete command is 
```bash
python train_broccoli_net.py --config-file configs/bmask_rcnn_R_101_FPN_1x.yaml --num-gpus 1 --eval-only MODEL.WEIGHTs output/bmask_rcnn_r101_1x/model_final.pth
```

**Comment by wmrenr** [comment]
Yes,you are right!

**Comment by wmrenr** [comment]
After training , how to choose the best  network weights  for evaluation?

**Comment by wmrenr** [comment]
> the complete command is
> 
> ```shell
> python train_broccoli_net.py --config-file configs/bmask_rcnn_R_101_FPN_1x.yaml --num-gpus 1 --eval-only MODEL.WEIGHTs output/bmask_rcnn_r101_1x/model_final.pth
> ```

I have now trained the model of my own dataset and evaluated it. How do I test it? The test doesn't seem to be reflected in your code.

**Comment by wondervictor** [comment]
Hi @wangxueping78, you only add `--eval-only` or `--eval` and the weights `MODEL.WEIGHTS` when using `train_net.py` or `train_broccoli_net.py`. If it doesn't work, could you provide more details?

**Comment by wmrenr** [comment]
> 

You mean evaluation, which I have already done. I mean I want to test, so to speak, to visually evaluation.

**Comment by wondervictor** [comment]
Hi @wangxueping78, you might check the `demo/demo.py` to obtain visualization results. However, you need to add lines after https://github.com/hustvl/BMaskR-CNN/blob/c74b0bd3ed47bf4aaa5c211c4e31eddc78fdc636/demo/demo.py#L24 
```python
from projects.BMaskR-CNN.bmaskrcnn import add_boundary_preserving_config
add_boundary_preserving_config(cfg)
```
to add BMask R-CNN configurations.
Then running 
```bash
mkdir results
python demo.py --config-file configs/bmask_rcnn_R_101_FPN_1x.yaml  --input [YOUR IMAGES] --output results --opts MODEL.WEIGHTS [YOUR MODEL WEIGHTS]
```

**Comment by wondervictor** [comment]
This issue will be closed, you can open a new issue if you have other problems or reopen it.
