### ISSUE TITLE
Pretrained model available?

### ISSUE THREAD

**Issue by AnnabelChen51** [hustvl/BMaskR-CNN#3]
Dear author,
Thank you very much for sharing your great work! I hope to know are there pretrained bmaskr-cnn models on Coco Dataset? I  saw  "COCO-InstanceSegmentation/bmask_rcnn_R_50_FPN_1x.yaml": "137260431/model_final_a54504.pkl" in the model_zoo.py. However, it cann't be downloaded.
 Your reply is greatly appreciated. Thank you very much!

**Comment by wondervictor** [comment]
@AnnabelChen51 Our README provides links for our pre-trained models. You can find models from [README](https://github.com/hustvl/BMaskR-CNN#coco)

**Comment by AnnabelChen51** [comment]
Sorry for missing that. Thank you very much！
