### ISSUE TITLE
where can I find the bmask_rcnn_R_50_FPN_1x.py file?

### ISSUE THREAD

**Issue by shwoo1219** [hustvl/BMaskR-CNN#4]
Thanks for sharing the nice code.
where can I find the bmask_rcnn_R_50_FPN_1x.py file?

**Comment by Syzygianinfern0** [comment]
https://github.com/hustvl/BMaskR-CNN/blob/master/projects/BMaskR-CNN/configs/bmask_rcnn_R_50_FPN_1x.yaml
You can find it here

**Comment by wondervictor** [comment]
Thank @Syzygianinfern0 
Code and config files are in the [project directory](https://github.com/hustvl/BMaskR-CNN/tree/master/projects/BMaskR-CNN)
