### ISSUE TITLE
KeyError: "No object named 'BoundaryROIHeads' found in 'ROI_HEADS' registry!"

### ISSUE THREAD

**Issue by PytaichukBohdan** [hustvl/BMaskR-CNN#6]
When trying to run the demo.py, keep getting registry related problems.
Have tried to modify the code in the detectron2 module, but unsuccessfully.

Is there anyone who encountered this problem? How did you solve it?

**Comment by PytaichukBohdan** [comment]
Or is there any other way to get alpha channel prediction from one image input?
Please let me know if there is one.

**Comment by wondervictor** [comment]
Hi，you need to import `bmaskrcnn` in `demo.py`.  Or directly copy the `demo.py` to `projects/BMask-RCNN` and import the `bmaskrcnn` module, then you can use the demo to obtain predictions

**Comment by PytaichukBohdan** [comment]
@wondervictor could you be so kind to provide with minimal working example?
Have been struggling to make it work on 1 custom image for the last 3 days

**Comment by charlescho64** [comment]
Hello, PytaichukBohdan 

Are you done with this issue? 

If done, how to get the result?

**Comment by wondervictor** [comment]
@charlescho64 @PytaichukBohdan Hi all, you need to import files/modules of BMask R-CNN to the `demo.py` to register the modules first.

**Comment by charlescho64** [comment]
@wondervictor  Thank you. I solved it. I am interesting in your working. 

other, could you give "cascade_bmask_rcnn_R_101_FPN_1x.yaml" to me because there is weight file but not config file in your site?

**Comment by wondervictor** [comment]
@charlescho64 config file for R101 has been updated [cascade_bmask_rcnn_R_101_FPN_1x.yaml](https://github.com/hustvl/BMaskR-CNN/blob/master/projects/BMaskR-CNN/configs/cascade_bmask_rcnn_R_101_FPN_1x.yaml)
