### ISSUE TITLE
边缘算子，请问数据集需要单独把边缘标注吗，还是就用分割的mask，然后模型自动用Laplacian算子来生成soft边界

### ISSUE THREAD

**Issue by qiaolegeke** [hustvl/BMaskR-CNN#8]

**Comment by wondervictor** [comment]
@qiaolegeke 不用再去标记边缘，会online计算mask的边缘作为标注，另外，也不是soft边界，laplace处理后会二值化

**Comment by wondervictor** [comment]
This issue is closed. If you have any question, you could reopen it.
